version: "3.8"

services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "${POSTGRES_PORT}:5432"

  web:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./app:/app  # hot reload for dev
    restart: unless-stopped

volumes:
  pgdata:
